[workspace]
resolver = "2"

members = [
    "contracts/counter",
    "contracts/token",
    "contracts/nft",
    "contracts/voting",
    "contracts/escrow",
    "contracts/multisig",
    "contracts/oracle",
    "contracts/amm",
    "contracts/auth",
    "contracts/events",
    "contracts/cross-contract/caller",
    "contracts/cross-contract/callee",
    "contracts/storage",
]

[workspace.dependencies]
soroban-sdk = { version = "27.0.6" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
